HomeTitle: Moodz

Close: Close

ShowAverages: Show Averages

NewMood: New Mood
CreateMood: Create Mood
MoodValue: Your Mood
MoodNotes: Notes
SaveMood: Save Mood
AddMoreMoodz: Add More Moodz
MoodMinimum: You must have at least 2 Moodz
YouOnlyHave: You only have:

OneDay: One Day
ThreeDay: Three Day
Week: Week
Month: Month
Year: Year

NewVariable: New Variable
CreateVariable: Create Variable
VariableName: Name
SaveVariable: Save Variable
ChooseVariable: Choose Variable
ShowVariable: Show Variable

NewVariableValue: New Value
VariableValueValue: Value
VariableValueNotes: Notes
SaveVariableValue: Save Value
