HomeTitle: Moodz

ShowMoodz: Show Moodz
ShowAverages: Show Averages

NewMood: New Mood
CreateMood: Create Mood
MoodValue: Your Mood
MoodNotes: Notes
SaveMood: Save Mood

ThreeDay: Three Day
Week: Week
Month: Month
Year: Year

NewVariable: New Variable
CreateVariable: Create Variable
VariableName: Name
SaveVariable: Save Variable
ChooseVariable: Choose Variable
ShowVariable: Show Variable

CreateVariableValue: New Value
VariableValueValue: Value
VariableValueNotes: Notes
SaveVariableValue: Save Value
