Default: &defaults
  database: moodz.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: moodz_test.sqlite3
  <<: *defaults

Staging:
  database: moodz_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: moodz_production.sqlite3
  poolsize: 100
  <<: *defaults
